Adam_optimizer:
  initial_lr: 0.01
  weight_decay: 1.0e-06
Dataset:
  num_locations: 20607
  num_users: 10000
  sequence_length: 20
  topic_num: 0
Embedding:
  base_dim: 16
Encoder:
  encoder_type: trans
Model:
  batch_size: 128
  epoch: 50
  seed: 1234
  test_epoch: 50
