Adam_optimizer:
  initial_lr: 0.01
  weight_decay: 1.0e-06
Dataset:
  num_locations: 2418
  num_users: 7800
  sequence_length: 20
  topic_num: 0
Embedding:
  base_dim: 32
Encoder:
  encoder_type: trans
Model:
  at_type: none
  batch_size: 128
  epoch: 50
  seed: 1234
  test_epoch: 50
